name: Java CI with Maven

on: [ push, pull_request ]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         -
            uses: actions/setup-java@v3
            with:
               distribution: 'temurin'
               java-version: 17
         - run: echo "ARTIFACT_NAME=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
         - run: echo "ARTIFACT_VERSION=$([[ "${GITHUB_REF_TYPE}" = "tag" ]] && echo "${GITHUB_REF_NAME}" || echo "${GITHUB_SHA:1:8}")" >> $GITHUB_ENV
         - run: mvn -B package --file pom.xml
         - run: mv -n target/*.jar target/${{ env.ARTIFACT_NAME }}-${{ env.ARTIFACT_VERSION }}.jar
         -
            uses: actions/upload-artifact@v3
            with:
               name: ${{ env.ARTIFACT_NAME }}-${{ env.ARTIFACT_VERSION }}
               path: target/${{ env.ARTIFACT_NAME }}-${{ env.ARTIFACT_VERSION }}.jar
